#
#	LampControl Configuration File
#	=====================================
#
#	Plugin by jacklink01 adapted from LumosMaxima
# 	Like this plugin? Donate! http://voidteam.net/donate :)
#
#	Need a new config file? Just delete this one and a new one will be created.
#

# The item ID of the item with which you would like players to be able to turn on lamps.
# (default: flint/steel 259)
lampControlItem: 259

# If set to true, then LampControl will check if players have permission, otherwise it will let everyone control lamps.
usePermissions: false

# In the event that you would like to prevent plates from affecting lamps, you may set these to false.
woodPlateControl: true
stonePlateControl: true

# When this is set to true, OP'd players can use their hand to control the lamps in addition to the item above.
# You may also give a player or group the 'lampcontrol.hand' permission.
opUsesHand: true

# Take the item from the player after they use it to turn on a lamp
takeItemOnUse: false

# Keep up to date! This plugin can notify you about updates and let you install them from in-game!
update-notification: true


# Don't touch this unless you wanna lose your config. :)
config-version: 2