name: LampControl
author: Granik24, jacklink01
version: 1.4
main: cz.granik24.LampControl.Main

commands:
   lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command> [off]
      aliases: [lc, lampcontrol]
   /lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command> [off]
      aliases: [/lc, /lampcontrol]