name: LampControl
author: Granik24, jacklink01
version: 3.0
main: cz.granik24.LampControl.Main

commands:
   lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command>
      aliases: [lc, lampcontrol]
   /lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command>
   /lc:
      description: Turn on lamps with WorldEdit
      usage: /<command>