name: LampControl
author: jacklink01, Granik24
version: 1.2-HoZFork
main: com.jacklinkproductions.LampControl.Main

commands:
   lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command>
      aliases: [lc, lampcontrol]
   /lamp:
      description: Turn on lamps with WorldEdit
      usage: /<command>
   /lc:
      description: Turn on lamps with WorldEdit
      usage: /<command>