name: LampControl
author: Ceph
version: 1.6
main: cz.ceph.LampControl.Main

commands:
   lamp:
      description: Turn on/off lamps with WorldEdit
      usage: /<command> [off]
      aliases: [lc, lampcontrol]
   /lamp:
      description: Turn on/off lamps with WorldEdit
      usage: /<command> [off]
      aliases: [/lc, /lampcontrol]