name: LampControl
authors: [Darkilen, Ceph]
version: ${spigot.plugin.version}
main: cz.ceph.LampControl.LampControl
api-version: 1.13

commands:
  lamp:
    description: Turn on/off lamps with WorldEdit
    usage: /<command> [off]
    aliases: [lc, lampcontrol]
  /lamp:
    description: Turn on/off lamps with WorldEdit
    usage: /<command> [off]
    aliases: [/lc, /lampcontrol]